projects:
  VisionAppSync:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: dramfozhqjb6xbzjco6ctfuetu
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://zqnyxinrlnhmpkf6s5gkql54am.appsync-api.us-east-1.amazonaws.com/graphql
